// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: content.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createEntry = `-- name: CreateEntry :exec
INSERT INTO entries (id, content_type_id, title, slug, status, author_id, parent_id, published_revision_id, created_at, updated_at, published_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateEntryParams struct {
	ID                  string
	ContentTypeID       string
	Title               string
	Slug                string
	Status              string
	AuthorID            string
	ParentID            sql.NullString
	PublishedRevisionID sql.NullString
	CreatedAt           string
	UpdatedAt           string
	PublishedAt         sql.NullString
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) error {
	_, err := q.db.ExecContext(ctx, createEntry,
		arg.ID,
		arg.ContentTypeID,
		arg.Title,
		arg.Slug,
		arg.Status,
		arg.AuthorID,
		arg.ParentID,
		arg.PublishedRevisionID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.PublishedAt,
	)
	return err
}

const createEntryDraft = `-- name: CreateEntryDraft :exec
INSERT INTO entry_drafts (entry_id, title, slug, document_json, version, updated_by, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateEntryDraftParams struct {
	EntryID      string
	Title        string
	Slug         string
	DocumentJson string
	Version      int64
	UpdatedBy    string
	UpdatedAt    string
}

func (q *Queries) CreateEntryDraft(ctx context.Context, arg CreateEntryDraftParams) error {
	_, err := q.db.ExecContext(ctx, createEntryDraft,
		arg.EntryID,
		arg.Title,
		arg.Slug,
		arg.DocumentJson,
		arg.Version,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	return err
}

const createRevision = `-- name: CreateRevision :exec
INSERT INTO revisions (id, entry_id, number, title, document_json, created_by, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateRevisionParams struct {
	ID           string
	EntryID      string
	Number       int64
	Title        string
	DocumentJson string
	CreatedBy    string
	CreatedAt    string
}

func (q *Queries) CreateRevision(ctx context.Context, arg CreateRevisionParams) error {
	_, err := q.db.ExecContext(ctx, createRevision,
		arg.ID,
		arg.EntryID,
		arg.Number,
		arg.Title,
		arg.DocumentJson,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const createRoute = `-- name: CreateRoute :exec
INSERT INTO routes (id, path, resource_type, resource_id, canonical, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateRouteParams struct {
	ID           string
	Path         string
	ResourceType string
	ResourceID   string
	Canonical    int64
	CreatedAt    string
	UpdatedAt    string
}

func (q *Queries) CreateRoute(ctx context.Context, arg CreateRouteParams) error {
	_, err := q.db.ExecContext(ctx, createRoute,
		arg.ID,
		arg.Path,
		arg.ResourceType,
		arg.ResourceID,
		arg.Canonical,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getContentTypeByHandle = `-- name: GetContentTypeByHandle :one
SELECT id, handle, name, schema_json, created_at, updated_at FROM content_types WHERE handle = ?
`

func (q *Queries) GetContentTypeByHandle(ctx context.Context, handle string) (ContentType, error) {
	row := q.db.QueryRowContext(ctx, getContentTypeByHandle, handle)
	var i ContentType
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.Name,
		&i.SchemaJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEntry = `-- name: GetEntry :one
SELECT id, content_type_id, title, slug, status, author_id, parent_id, published_revision_id, created_at, updated_at, published_at FROM entries WHERE id = ?
`

func (q *Queries) GetEntry(ctx context.Context, id string) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getEntry, id)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.ContentTypeID,
		&i.Title,
		&i.Slug,
		&i.Status,
		&i.AuthorID,
		&i.ParentID,
		&i.PublishedRevisionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const getEntryByType = `-- name: GetEntryByType :one
SELECT e.id, e.content_type_id, e.title, e.slug, e.status, e.author_id, e.parent_id, e.published_revision_id, e.created_at, e.updated_at, e.published_at
FROM entries e JOIN content_types ct ON ct.id = e.content_type_id WHERE e.id = ? AND ct.handle = ?
`

type GetEntryByTypeParams struct {
	ID     string
	Handle string
}

func (q *Queries) GetEntryByType(ctx context.Context, arg GetEntryByTypeParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getEntryByType, arg.ID, arg.Handle)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.ContentTypeID,
		&i.Title,
		&i.Slug,
		&i.Status,
		&i.AuthorID,
		&i.ParentID,
		&i.PublishedRevisionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const getEntryDraft = `-- name: GetEntryDraft :one
SELECT entry_id, title, slug, document_json, version, updated_by, updated_at FROM entry_drafts WHERE entry_id = ?
`

func (q *Queries) GetEntryDraft(ctx context.Context, entryID string) (EntryDraft, error) {
	row := q.db.QueryRowContext(ctx, getEntryDraft, entryID)
	var i EntryDraft
	err := row.Scan(
		&i.EntryID,
		&i.Title,
		&i.Slug,
		&i.DocumentJson,
		&i.Version,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getEntryRoute = `-- name: GetEntryRoute :one
SELECT id, path, resource_type, resource_id, canonical, created_at, updated_at
FROM routes WHERE resource_type = 'entry' AND resource_id = ? AND canonical = 1
`

func (q *Queries) GetEntryRoute(ctx context.Context, resourceID string) (Route, error) {
	row := q.db.QueryRowContext(ctx, getEntryRoute, resourceID)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.ResourceType,
		&i.ResourceID,
		&i.Canonical,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestRevision = `-- name: GetLatestRevision :one
SELECT id, entry_id, number, title, document_json, created_by, created_at FROM revisions WHERE entry_id = ? ORDER BY number DESC LIMIT 1
`

func (q *Queries) GetLatestRevision(ctx context.Context, entryID string) (Revision, error) {
	row := q.db.QueryRowContext(ctx, getLatestRevision, entryID)
	var i Revision
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.Number,
		&i.Title,
		&i.DocumentJson,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getRevision = `-- name: GetRevision :one
SELECT id, entry_id, number, title, document_json, created_by, created_at FROM revisions WHERE id = ?
`

func (q *Queries) GetRevision(ctx context.Context, id string) (Revision, error) {
	row := q.db.QueryRowContext(ctx, getRevision, id)
	var i Revision
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.Number,
		&i.Title,
		&i.DocumentJson,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listEntriesByType = `-- name: ListEntriesByType :many
SELECT e.id, e.content_type_id, e.title, e.slug, e.status, e.author_id, e.parent_id, e.published_revision_id, e.created_at, e.updated_at, e.published_at,
       r.path, u.display_name
FROM entries e JOIN routes r ON r.resource_type = 'entry' AND r.resource_id = e.id AND r.canonical = 1
JOIN users u ON u.id = e.author_id
WHERE e.content_type_id = ? ORDER BY e.updated_at DESC
`

type ListEntriesByTypeRow struct {
	ID                  string
	ContentTypeID       string
	Title               string
	Slug                string
	Status              string
	AuthorID            string
	ParentID            sql.NullString
	PublishedRevisionID sql.NullString
	CreatedAt           string
	UpdatedAt           string
	PublishedAt         sql.NullString
	Path                string
	DisplayName         string
}

func (q *Queries) ListEntriesByType(ctx context.Context, contentTypeID string) ([]ListEntriesByTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, listEntriesByType, contentTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntriesByTypeRow
	for rows.Next() {
		var i ListEntriesByTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.ContentTypeID,
			&i.Title,
			&i.Slug,
			&i.Status,
			&i.AuthorID,
			&i.ParentID,
			&i.PublishedRevisionID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
			&i.Path,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRevisions = `-- name: ListRevisions :many
SELECT r.id, r.entry_id, r.number, r.title, r.document_json, r.created_by, r.created_at, u.display_name
FROM revisions r JOIN users u ON u.id = r.created_by WHERE r.entry_id = ? ORDER BY r.number DESC
`

type ListRevisionsRow struct {
	ID           string
	EntryID      string
	Number       int64
	Title        string
	DocumentJson string
	CreatedBy    string
	CreatedAt    string
	DisplayName  string
}

func (q *Queries) ListRevisions(ctx context.Context, entryID string) ([]ListRevisionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRevisions, entryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRevisionsRow
	for rows.Next() {
		var i ListRevisionsRow
		if err := rows.Scan(
			&i.ID,
			&i.EntryID,
			&i.Number,
			&i.Title,
			&i.DocumentJson,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextRevisionNumber = `-- name: NextRevisionNumber :one
SELECT COALESCE(MAX(number), 0) + 1 FROM revisions WHERE entry_id = ?
`

func (q *Queries) NextRevisionNumber(ctx context.Context, entryID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextRevisionNumber, entryID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const resolvePublishedRoute = `-- name: ResolvePublishedRoute :one
SELECT e.id, e.content_type_id, e.title, e.slug, e.status, e.author_id, e.parent_id, e.published_revision_id, e.created_at, e.updated_at, e.published_at,
       r.id, r.entry_id, r.number, r.title, r.document_json, r.created_by, r.created_at
FROM routes route
JOIN entries e ON e.id = route.resource_id
JOIN revisions r ON r.id = e.published_revision_id
WHERE route.path = ? AND route.resource_type = 'entry' AND route.canonical = 1 AND e.status = 'published'
`

type ResolvePublishedRouteRow struct {
	ID                  string
	ContentTypeID       string
	Title               string
	Slug                string
	Status              string
	AuthorID            string
	ParentID            sql.NullString
	PublishedRevisionID sql.NullString
	CreatedAt           string
	UpdatedAt           string
	PublishedAt         sql.NullString
	ID_2                string
	EntryID             string
	Number              int64
	Title_2             string
	DocumentJson        string
	CreatedBy           string
	CreatedAt_2         string
}

func (q *Queries) ResolvePublishedRoute(ctx context.Context, path string) (ResolvePublishedRouteRow, error) {
	row := q.db.QueryRowContext(ctx, resolvePublishedRoute, path)
	var i ResolvePublishedRouteRow
	err := row.Scan(
		&i.ID,
		&i.ContentTypeID,
		&i.Title,
		&i.Slug,
		&i.Status,
		&i.AuthorID,
		&i.ParentID,
		&i.PublishedRevisionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.ID_2,
		&i.EntryID,
		&i.Number,
		&i.Title_2,
		&i.DocumentJson,
		&i.CreatedBy,
		&i.CreatedAt_2,
	)
	return i, err
}

const updateEntry = `-- name: UpdateEntry :exec
UPDATE entries SET title = ?, slug = ?, status = ?, updated_at = ?, published_at = ?, published_revision_id = ? WHERE id = ?
`

type UpdateEntryParams struct {
	Title               string
	Slug                string
	Status              string
	UpdatedAt           string
	PublishedAt         sql.NullString
	PublishedRevisionID sql.NullString
	ID                  string
}

func (q *Queries) UpdateEntry(ctx context.Context, arg UpdateEntryParams) error {
	_, err := q.db.ExecContext(ctx, updateEntry,
		arg.Title,
		arg.Slug,
		arg.Status,
		arg.UpdatedAt,
		arg.PublishedAt,
		arg.PublishedRevisionID,
		arg.ID,
	)
	return err
}

const updateEntryDraft = `-- name: UpdateEntryDraft :execrows
UPDATE entry_drafts SET title = ?, slug = ?, document_json = ?, version = version + 1, updated_by = ?, updated_at = ?
WHERE entry_id = ? AND version = ?
`

type UpdateEntryDraftParams struct {
	Title        string
	Slug         string
	DocumentJson string
	UpdatedBy    string
	UpdatedAt    string
	EntryID      string
	Version      int64
}

func (q *Queries) UpdateEntryDraft(ctx context.Context, arg UpdateEntryDraftParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateEntryDraft,
		arg.Title,
		arg.Slug,
		arg.DocumentJson,
		arg.UpdatedBy,
		arg.UpdatedAt,
		arg.EntryID,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateEntryRoute = `-- name: UpdateEntryRoute :exec
UPDATE routes SET path = ?, updated_at = ? WHERE resource_type = 'entry' AND resource_id = ? AND canonical = 1
`

type UpdateEntryRouteParams struct {
	Path       string
	UpdatedAt  string
	ResourceID string
}

func (q *Queries) UpdateEntryRoute(ctx context.Context, arg UpdateEntryRouteParams) error {
	_, err := q.db.ExecContext(ctx, updateEntryRoute, arg.Path, arg.UpdatedAt, arg.ResourceID)
	return err
}
