// Code generated by sqlc. DO NOT EDIT.
package sqlc

import (
	"context"
	"database/sql"
)

func (q *Queries) GetContentTypeByHandle(ctx context.Context, handle string) (ContentType, error) {
	var v ContentType
	err := q.db.QueryRowContext(ctx, `SELECT id, handle, name, schema_json, created_at, updated_at FROM content_types WHERE handle = ?`, handle).Scan(&v.ID, &v.Handle, &v.Name, &v.SchemaJson, &v.CreatedAt, &v.UpdatedAt)
	return v, err
}
func (q *Queries) GetEntry(ctx context.Context, id string) (Entry, error) {
	var v Entry
	err := q.db.QueryRowContext(ctx, `SELECT id, content_type_id, title, slug, status, author_id, parent_id, published_revision_id, created_at, updated_at, published_at FROM entries WHERE id = ?`, id).Scan(&v.ID, &v.ContentTypeID, &v.Title, &v.Slug, &v.Status, &v.AuthorID, &v.ParentID, &v.PublishedRevisionID, &v.CreatedAt, &v.UpdatedAt, &v.PublishedAt)
	return v, err
}
func (q *Queries) GetEntryRoute(ctx context.Context, resourceID string) (Route, error) {
	var v Route
	err := q.db.QueryRowContext(ctx, `SELECT id,path,resource_type,resource_id,canonical,created_at,updated_at FROM routes WHERE resource_type='entry' AND resource_id=? AND canonical=1`, resourceID).Scan(&v.ID, &v.Path, &v.ResourceType, &v.ResourceID, &v.Canonical, &v.CreatedAt, &v.UpdatedAt)
	return v, err
}

type ListEntriesByTypeRow struct {
	Entry
	Path, DisplayName string
}

func (q *Queries) ListEntriesByType(ctx context.Context, typeID string) ([]ListEntriesByTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, `SELECT e.id,e.content_type_id,e.title,e.slug,e.status,e.author_id,e.parent_id,e.published_revision_id,e.created_at,e.updated_at,e.published_at,r.path,u.display_name FROM entries e JOIN routes r ON r.resource_type='entry' AND r.resource_id=e.id AND r.canonical=1 JOIN users u ON u.id=e.author_id WHERE e.content_type_id=? ORDER BY e.updated_at DESC`, typeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var result []ListEntriesByTypeRow
	for rows.Next() {
		var v ListEntriesByTypeRow
		if err := rows.Scan(&v.ID, &v.ContentTypeID, &v.Title, &v.Slug, &v.Status, &v.AuthorID, &v.ParentID, &v.PublishedRevisionID, &v.CreatedAt, &v.UpdatedAt, &v.PublishedAt, &v.Path, &v.DisplayName); err != nil {
			return nil, err
		}
		result = append(result, v)
	}
	return result, rows.Err()
}

type CreateEntryParams struct {
	ID, ContentTypeID, Title, Slug, Status, AuthorID string
	ParentID, PublishedRevisionID                    sql.NullString
	CreatedAt, UpdatedAt                             string
	PublishedAt                                      sql.NullString
}

func (q *Queries) CreateEntry(ctx context.Context, v CreateEntryParams) error {
	_, err := q.db.ExecContext(ctx, `INSERT INTO entries (id,content_type_id,title,slug,status,author_id,parent_id,published_revision_id,created_at,updated_at,published_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)`, v.ID, v.ContentTypeID, v.Title, v.Slug, v.Status, v.AuthorID, v.ParentID, v.PublishedRevisionID, v.CreatedAt, v.UpdatedAt, v.PublishedAt)
	return err
}

type UpdateEntryParams struct {
	Title, Slug, Status, UpdatedAt   string
	PublishedAt, PublishedRevisionID sql.NullString
	ID                               string
}

func (q *Queries) UpdateEntry(ctx context.Context, v UpdateEntryParams) error {
	_, err := q.db.ExecContext(ctx, `UPDATE entries SET title=?,slug=?,status=?,updated_at=?,published_at=?,published_revision_id=? WHERE id=?`, v.Title, v.Slug, v.Status, v.UpdatedAt, v.PublishedAt, v.PublishedRevisionID, v.ID)
	return err
}
func (q *Queries) NextRevisionNumber(ctx context.Context, entryID string) (int64, error) {
	var n int64
	err := q.db.QueryRowContext(ctx, `SELECT COALESCE(MAX(number),0)+1 FROM revisions WHERE entry_id=?`, entryID).Scan(&n)
	return n, err
}

type CreateRevisionParams struct {
	ID, EntryID                               string
	Number                                    int64
	Title, DocumentJson, CreatedBy, CreatedAt string
}

func (q *Queries) CreateRevision(ctx context.Context, v CreateRevisionParams) error {
	_, err := q.db.ExecContext(ctx, `INSERT INTO revisions (id,entry_id,number,title,document_json,created_by,created_at) VALUES (?,?,?,?,?,?,?)`, v.ID, v.EntryID, v.Number, v.Title, v.DocumentJson, v.CreatedBy, v.CreatedAt)
	return err
}

type ListRevisionsRow struct {
	Revision
	DisplayName string
}

func (q *Queries) ListRevisions(ctx context.Context, entryID string) ([]ListRevisionsRow, error) {
	rows, err := q.db.QueryContext(ctx, `SELECT r.id,r.entry_id,r.number,r.title,r.document_json,r.created_by,r.created_at,u.display_name FROM revisions r JOIN users u ON u.id=r.created_by WHERE r.entry_id=? ORDER BY r.number DESC`, entryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var result []ListRevisionsRow
	for rows.Next() {
		var v ListRevisionsRow
		if err := rows.Scan(&v.ID, &v.EntryID, &v.Number, &v.Title, &v.DocumentJson, &v.CreatedBy, &v.CreatedAt, &v.DisplayName); err != nil {
			return nil, err
		}
		result = append(result, v)
	}
	return result, rows.Err()
}

type CreateRouteParams struct {
	ID, Path, ResourceType, ResourceID string
	Canonical                          int64
	CreatedAt, UpdatedAt               string
}

func (q *Queries) CreateRoute(ctx context.Context, v CreateRouteParams) error {
	_, err := q.db.ExecContext(ctx, `INSERT INTO routes (id,path,resource_type,resource_id,canonical,created_at,updated_at) VALUES (?,?,?,?,?,?,?)`, v.ID, v.Path, v.ResourceType, v.ResourceID, v.Canonical, v.CreatedAt, v.UpdatedAt)
	return err
}

type UpdateEntryRouteParams struct{ Path, UpdatedAt, ResourceID string }

func (q *Queries) UpdateEntryRoute(ctx context.Context, v UpdateEntryRouteParams) error {
	_, err := q.db.ExecContext(ctx, `UPDATE routes SET path=?,updated_at=? WHERE resource_type='entry' AND resource_id=? AND canonical=1`, v.Path, v.UpdatedAt, v.ResourceID)
	return err
}
