// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type ContentType struct {
	ID         string
	Handle     string
	Name       string
	SchemaJson string
	CreatedAt  string
	UpdatedAt  string
}

type Entry struct {
	ID                  string
	ContentTypeID       string
	Title               string
	Slug                string
	Status              string
	AuthorID            string
	ParentID            sql.NullString
	PublishedRevisionID sql.NullString
	CreatedAt           string
	UpdatedAt           string
	PublishedAt         sql.NullString
}

type Installation struct {
	ID        int64
	CreatedAt string
}

type Revision struct {
	ID           string
	EntryID      string
	Number       int64
	Title        string
	DocumentJson string
	CreatedBy    string
	CreatedAt    string
}

type Route struct {
	ID           string
	Path         string
	ResourceType string
	ResourceID   string
	Canonical    int64
	CreatedAt    string
	UpdatedAt    string
}

type SchemaMigration struct {
	Version   int64
	AppliedAt string
}

type Session struct {
	ID         string
	UserID     string
	TokenHash  string
	ExpiresAt  string
	CreatedAt  string
	LastSeenAt string
}

type User struct {
	ID           string
	Email        string
	Username     string
	PasswordHash string
	DisplayName  string
	Role         string
	CreatedAt    string
	UpdatedAt    string
}
