// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import "database/sql"

type Installation struct {
	ID        int64
	CreatedAt string
}

type SchemaMigration struct {
	Version   int64
	AppliedAt string
}

type Session struct {
	ID         string
	UserID     string
	TokenHash  string
	ExpiresAt  string
	CreatedAt  string
	LastSeenAt string
}

type User struct {
	ID           string
	Email        string
	Username     string
	PasswordHash string
	DisplayName  string
	Role         string
	CreatedAt    string
	UpdatedAt    string
}

type ContentType struct{ ID, Handle, Name, SchemaJson, CreatedAt, UpdatedAt string }
type Entry struct {
	ID, ContentTypeID, Title, Slug, Status, AuthorID string
	ParentID, PublishedRevisionID                    sql.NullString
	CreatedAt, UpdatedAt                             string
	PublishedAt                                      sql.NullString
}
type Revision struct {
	ID, EntryID                               string
	Number                                    int64
	Title, DocumentJson, CreatedBy, CreatedAt string
}
type Route struct {
	ID, Path, ResourceType, ResourceID string
	Canonical                          int64
	CreatedAt, UpdatedAt               string
}
