// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

type Installation struct {
	ID        int64
	CreatedAt string
}

type SchemaMigration struct {
	Version   int64
	AppliedAt string
}

type Session struct {
	ID         string
	UserID     string
	TokenHash  string
	ExpiresAt  string
	CreatedAt  string
	LastSeenAt string
}

type User struct {
	ID           string
	Email        string
	Username     string
	PasswordHash string
	DisplayName  string
	Role         string
	CreatedAt    string
	UpdatedAt    string
}
