// Code generated by sqlc. DO NOT EDIT.
package sqlc

import "context"

type SitePresentation struct {
	ID                                 int64
	ActiveTheme, StylesJson, CustomCss string
	Version                            int64
	UpdatedAt                          string
}

const getSitePresentation = `-- name: GetSitePresentation :one
SELECT id, active_theme, styles_json, custom_css, version, updated_at FROM site_presentation WHERE id = 1
`

func (q *Queries) GetSitePresentation(ctx context.Context) (SitePresentation, error) {
	var i SitePresentation
	err := q.db.QueryRowContext(ctx, getSitePresentation).Scan(&i.ID, &i.ActiveTheme, &i.StylesJson, &i.CustomCss, &i.Version, &i.UpdatedAt)
	return i, err
}

const updateSitePresentation = `-- name: UpdateSitePresentation :execrows
UPDATE site_presentation SET active_theme = ?, styles_json = ?, custom_css = ?, version = version + 1, updated_at = ? WHERE id = 1 AND version = ?
`

type UpdateSitePresentationParams struct {
	ActiveTheme, StylesJson, CustomCss, UpdatedAt string
	Version                                       int64
}

func (q *Queries) UpdateSitePresentation(ctx context.Context, arg UpdateSitePresentationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSitePresentation, arg.ActiveTheme, arg.StylesJson, arg.CustomCss, arg.UpdatedAt, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
