// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, email, username, password_hash, display_name, role, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	ID           string
	Email        string
	Username     string
	PasswordHash string
	DisplayName  string
	Role         string
	CreatedAt    string
	UpdatedAt    string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
		arg.DisplayName,
		arg.Role,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getUserByLogin = `-- name: GetUserByLogin :one
SELECT id, email, username, password_hash, display_name, role, created_at, updated_at
FROM users WHERE email = ? OR username = ? LIMIT 1
`

type GetUserByLoginParams struct {
	Email    string
	Username string
}

func (q *Queries) GetUserByLogin(ctx context.Context, arg GetUserByLoginParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByLogin, arg.Email, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserBySessionTokenHash = `-- name: GetUserBySessionTokenHash :one
SELECT u.id, u.email, u.username, u.password_hash, u.display_name, u.role, u.created_at, u.updated_at
FROM users u JOIN sessions s ON s.user_id = u.id
WHERE s.token_hash = ? AND s.expires_at > ? LIMIT 1
`

type GetUserBySessionTokenHashParams struct {
	TokenHash string
	ExpiresAt string
}

func (q *Queries) GetUserBySessionTokenHash(ctx context.Context, arg GetUserBySessionTokenHashParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserBySessionTokenHash, arg.TokenHash, arg.ExpiresAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
