// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, email, username, password_hash, display_name, role, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	ID           string
	Email        string
	Username     string
	PasswordHash string
	DisplayName  string
	Role         string
	CreatedAt    string
	UpdatedAt    string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
		arg.DisplayName,
		arg.Role,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getUserByEmail = `SELECT id, email, username, password_hash, display_name, role, created_at, updated_at FROM users WHERE email = ? LIMIT 1`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `SELECT id, email, username, password_hash, display_name, role, created_at, updated_at FROM users WHERE username = ? LIMIT 1`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.Username, &i.PasswordHash, &i.DisplayName, &i.Role, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const createInstallation = `INSERT INTO installation (id, created_at) VALUES (1, ?)`

func (q *Queries) CreateInstallation(ctx context.Context, createdAt string) error {
	_, err := q.db.ExecContext(ctx, createInstallation, createdAt)
	return err
}

const isConfigured = `SELECT EXISTS(SELECT 1 FROM installation WHERE id = 1)`

func (q *Queries) IsConfigured(ctx context.Context) (bool, error) {
	var configured bool
	err := q.db.QueryRowContext(ctx, isConfigured).Scan(&configured)
	return configured, err
}

const getUserBySessionTokenHash = `-- name: GetUserBySessionTokenHash :one
SELECT u.id, u.email, u.username, u.password_hash, u.display_name, u.role, u.created_at, u.updated_at
FROM users u JOIN sessions s ON s.user_id = u.id
WHERE s.token_hash = ? AND s.expires_at > ? LIMIT 1
`

type GetUserBySessionTokenHashParams struct {
	TokenHash string
	ExpiresAt string
}

func (q *Queries) GetUserBySessionTokenHash(ctx context.Context, arg GetUserBySessionTokenHashParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserBySessionTokenHash, arg.TokenHash, arg.ExpiresAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
